Repository kubernetes-sigs/wg-serving, pull requests merged in 2024-08, with the labels that each got.

#3 Initial readme
  serving-catalog/OWNERS
  serving-catalog/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#2 Initial kustomized blueprints commit
  serving-catalog/README.md
  serving-catalog/catalog.md
  serving-catalog/core/deployment/base/deployment.yaml
  serving-catalog/core/deployment/base/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/1-L4/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/1-L4/l4.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/2-L4/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/2-L4/l4.yaml
  serving-catalog/core/deployment/components/gke/resources/tpu/v5e-2x4/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/tpu/v5e-2x4/v5e-2x4.yaml
  serving-catalog/core/deployment/jetstream/base/deployment.patch.yaml
  serving-catalog/core/deployment/jetstream/base/job.yaml
  serving-catalog/core/deployment/jetstream/base/kustomization.yaml
  serving-catalog/core/deployment/jetstream/base/service.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/base/deployment.patch.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/base/job.patch.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/base/kustomization.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/base/service.patch.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/README.md
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/deployment.patch.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/job.patch.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/kustomization.yaml
  serving-catalog/core/deployment/vllm/base/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/base/kustomization.yaml
  serving-catalog/core/deployment/vllm/base/service.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/base/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/base/kustomization.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/base/service.patch.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/gke/README.md
  serving-catalog/core/deployment/vllm/gemma-2b/gke/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/gke/kustomization.yaml
  serving-catalog/hack/validate
Labels: cncf-cla: yes, approved, lgtm, size/L

#7 Initialize KServe folder in serving-catalog
  serving-catalog/README.md
  serving-catalog/kserve/inferenceservice/README.md
  serving-catalog/kserve/servingruntime/README.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#6 Update README
  serving-catalog/README.md
  serving-catalog/core/deployment/vllm/gemma-2b/gke/README.md
Labels: cncf-cla: yes, approved, size/S, lgtm, tide/merge-method-squash

#5 Add llama3-8b vLLM support
  serving-catalog/catalog.md
  serving-catalog/core/deployment/vllm/llama3-8b/base/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/base/kustomization.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/base/service.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/gke/README.md
  serving-catalog/core/deployment/vllm/llama3-8b/gke/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/gke/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M, tide/merge-method-squash
