Repository kubernetes-sigs/wg-serving, pull requests merged in 2024-10, with the labels that each got.

#16 Fix `ai.gke.io/inference-server` label
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/deployment.patch.yaml
  serving-catalog/core/deployment/jetstream/llama3-8b/gke/deployment.patch.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#20 Update vllm entrypoint to be metrics compatible
  serving-catalog/core/deployment/vllm/base/deployment.patch.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#22 Add Jason (jjk-g) to Serving Catalog approvers
  serving-catalog/OWNERS
Labels: cncf-cla: yes, approved, size/XS

#24 Configure prometheus_port for both jetstream jax and pytorch servers
  serving-catalog/core/deployment/jetstream/gemma-7b-it/base/deployment.patch.yaml
  serving-catalog/core/deployment/jetstream/llama3-8b/base/deployment.patch.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#23 Add readiness probe to vLLM base
  serving-catalog/core/deployment/vllm/base/deployment.patch.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#21 [Serving Catalog] Add llama3-70b support for vllm
  serving-catalog/catalog.md
  serving-catalog/core/deployment/components/gke/resources/gpu/8-L4/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/8-L4/l4.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/base/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/base/kustomization.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/base/service.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/gke/README.md
  serving-catalog/core/deployment/vllm/llama3-70b/gke/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/gke/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/L

#25 [Serving Catalog] Update vllm base deployment label
  serving-catalog/core/deployment/vllm/llama3-70b/base/deployment.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/base/deployment.patch.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#15 add HorizontalPodAutoscaler stub to catalog
  serving-catalog/core/deployment/components/hpa/base/hpa.yaml
  serving-catalog/core/deployment/components/hpa/base/kustomization.yaml
  serving-catalog/core/deployment/components/hpa/jetstream/token-latency/hpa.patch.yaml
  serving-catalog/core/deployment/components/hpa/jetstream/token-latency/kustomization.yaml
  serving-catalog/core/deployment/components/hpa/vllm/token-latency/hpa.patch.yaml
  serving-catalog/core/deployment/components/hpa/vllm/token-latency/kustomization.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/hpa.patch.yaml
  serving-catalog/core/deployment/jetstream/gemma-7b-it/gke/kustomization.yaml
  serving-catalog/core/deployment/jetstream/llama3-8b/gke/hpa.patch.yaml
  serving-catalog/core/deployment/jetstream/llama3-8b/gke/kustomization.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/gke/hpa.patch.yaml
  serving-catalog/core/deployment/vllm/gemma-2b/gke/kustomization.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/gke/hpa.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-70b/gke/kustomization.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/gke/hpa.patch.yaml
  serving-catalog/core/deployment/vllm/llama3-8b/gke/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/L
