Repository kubernetes-sigs/wg-serving, pull requests merged in 2025-10, with the labels that each got.

#48 Adding XLA cache for vLLM
  serving-catalog/core/deployment/components/storage/vllm/tpu/xla-cache/deployment.patch.yaml
  serving-catalog/core/deployment/components/storage/vllm/tpu/xla-cache/kustomization.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#56 changed dir of xla cache to be inside the volume mount
  serving-catalog/core/deployment/components/storage/vllm/tpu/xla-cache/deployment.patch.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#58 Add more gke gpu resource components
  serving-catalog/core/deployment/components/gke/resources/gpu/1-A100-40GB/a100-40gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/1-A100-40GB/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/1-H200-141GB/h200-141gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/1-H200-141GB/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/2-A100-40GB/a100-40gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/2-A100-40GB/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/2-H100-80GB/h100-80gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/2-H100-80GB/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/4-A100-40GB/a100-40gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/4-A100-40GB/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/8-A100-40GB/a100-40gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/8-A100-40GB/kustomization.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/8-H200-141GB/h200-141gb.yaml
  serving-catalog/core/deployment/components/gke/resources/gpu/8-H200-141GB/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/L
